version: '3'

services:
  apitemplate:
    image: apitemplate:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSetting__ConnectionString=mongodb://mongodb:27017
      - MongoDbSetting__Database=customerarea
    

  odataserver:
    image: odataserver:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSetting__ConnectionString=mongodb://mongodb:27017
      - MongoDbSetting__Database=customerarea
    
  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb